version: '3'
services:
  ioc-validator-new:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./results:/app/results
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  redis_data: